version: '3'
services:
  app:
    build: ./
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "./gradlew bootRun"
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db/jersey_db"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: jersey_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
      - mysql-datastore:/var/lib/mysql
volumes:
  mysql-datastore:
    driver: local