spring:
  profiles:
    active: localhost

---
spring:
  datasource:
    initialization–mode: always
    url: jdbc:mysql://localhost:3306/jersey_db?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  datasource:
    url: jdbc:mysql://db/jersey_db?useUnicode=true&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

