name: Test and Checkstyle
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shutdown MySQL
      run: sudo service mysql stop
    - name: Start docker-compose
      run: |
       docker-compose build
       docker-compose up -d
       docker exec jersey_app_1 ./gradlew build
           
